#ifndef CONFIG
#define CONFIG

// DEVICE ADDRESS

#define DEVICE_ADDRESS 0x01

// REQUEST DATA CODE

#define REQUEST_DATA 0x23

// SEND DATA 

#define SEND_DATA 0x16

// REQUEST DADA SUB-CODES

#define REQUEST_INTERNAL_TEMPERATURE 0xc1
#define REQUEST_REFERENCE_TEMPERATURE 0xc2
#define REQUEST_USER_INPUTS 0xc3

// SEND DADA SUB-CODES


#define SEND_CONTROL_SIGN 0xD1 
#define SEND_REFERENCE_SIGN 0xD2
#define SEND_SISTEM_STATE 0xD3
#define SEND_MODE 0xD4



#endif
